In [1]:
import pandas as pd

fp = "G:\\My Drive\\Darby Work\\XRF fundamentals vs. MVA\\"

In [2]:
rmsep_results = pd.read_csv(fp+"full_results_table.csv")

In [3]:
rmsep_results

,element,filter,regression,num_range,LOB,LOD,LOQ,avg_comp,RMSEP,R2
0,Al2O3,O1,lasso,0-750,13.094738,26.269079,79.603270,NaN,NaN,Not enough test samples above LOQ
1,CaO,O1,lasso,0-750,0.666077,1.336204,4.049102,9.454688,3.291960,-0.3168424920706623
2,Fe2O3,O1,lasso,0-750,2.308474,4.630982,14.033278,15.456818,1.092613,-0.19005994307622842
3,MgO,O1,lasso,0-750,4.349767,8.725976,26.442351,30.976400,2.422160,-1.6960224589882116
4,MnO,O1,lasso,0-750,0.059618,0.119599,0.362420,1.556667,1.040181,0.707981073831928
...,...,...,...,...,...,...,...,...,...,...
114,V,O2,lasso,all,23.505945,47.154783,142.893281,NaN,NaN,NaN
115,W,O2,lasso,all,1.319354,2.646728,8.020389,NaN,NaN,NaN
116,Y,O2,lasso,all,0.972068,1.950045,5.909227,NaN,NaN,NaN
117,Zn,O2,lasso,all,6.648001,13.336415,40.413379,NaN,NaN,NaN
118,U,O2,lasso,all,0.317572,0.637074,1.930527,NaN,NaN,NaN